- name: provision postgresql deployment in k8s
  hosts: localhost
  gather_facts: no
  tasks:
  - name: install nginx ingress controller 
    shell: |
      helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
        --version 4.4.2 \
        --namespace ingress \
        --create-namespace \
        -f ./ingress/nginx_values.yaml
  - name: create namespace backend
    shell: kubectl create ns backend
  - name: deploy secret 
    shell: kubectl apply -f secret.yaml 
  - name: deploy posgresql 
    shell: kubectl apply -f postgres

  
  