- name: provision postgresql deployment in k8s
  hosts: localhost
  gather_facts: no
  vars:
    posgres: false
    server: false
    trigger_replace: false
    prometheus: false

  tasks:
  - name: provision postgresql deployment in k8s
    when: posgres
    block:
    - name: install nginx ingress controller 
      shell: |
        helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
          --version 4.4.2 \
          --namespace ingress \
          --create-namespace \
          -f ./ingress/nginx_values.yaml
    - name: create namespace backend and app 
      shell: kubectl apply -f prometheus/watched_ns/
    - name: deploy secret 
      shell: kubectl apply -f secret.yaml 
    - name: deploy posgresql 
      shell: kubectl apply -f postgres

  - name: deploy REST api server and gRPC server
    when: server
    block:
    - name: deploy the secret for username and password 
      shell: kubectl apply -f username-secret.yaml
    - name: deploy the yaml file
      shell: kubectl apply -f rest_grpc_app/


  - name: populate the rRPC client file
    when: trigger_replace
    block:
    - name: get the nlb link
      shell: kubectl get svc/go-app-service  -n app -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}'
      register: nlb_link_gRPC
      changed_when: false
    - name: Replace placeholder in file with NLB link
      template:
        src: ./gRPC_client/main.go.j2
        dest: ./gRPC_client/main.go
        mode: '0644'
      vars:
        nlb_link: "{{ nlb_link_gRPC.stdout }}"
  
  - name: provision kube-prometheus-stack
    when: prometheus
    block:
    - name: create monitoring namespace
      shell: kubectl create ns monitoring 
    - name: helm install kube-prometheus-stack
      # shell: helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring --version v0.67.1 -f ./prometheus/kube-prometheus-stack-values.yaml --version=v0.67.1 
      shell: helm install prometheus-stack prometheus-community/kube-prometheus-stack \
              --version 45.31.0 \
              --namespace monitoring \
              --create-namespace \
              -f ./prometheus/custom_values.yaml
    
      


      

  
  