// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gRPC_microservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AccountManagementClient is the client API for AccountManagement service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountManagementClient interface {
	CreateAccount(ctx context.Context, in *NewAccount, opts ...grpc.CallOption) (*Account, error)
	GetAccount(ctx context.Context, in *GetAccountParams, opts ...grpc.CallOption) (*AccountList, error)
}

type accountManagementClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountManagementClient(cc grpc.ClientConnInterface) AccountManagementClient {
	return &accountManagementClient{cc}
}

func (c *accountManagementClient) CreateAccount(ctx context.Context, in *NewAccount, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/account_proto.AccountManagement/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountManagementClient) GetAccount(ctx context.Context, in *GetAccountParams, opts ...grpc.CallOption) (*AccountList, error) {
	out := new(AccountList)
	err := c.cc.Invoke(ctx, "/account_proto.AccountManagement/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountManagementServer is the server API for AccountManagement service.
// All implementations must embed UnimplementedAccountManagementServer
// for forward compatibility
type AccountManagementServer interface {
	CreateAccount(context.Context, *NewAccount) (*Account, error)
	GetAccount(context.Context, *GetAccountParams) (*AccountList, error)
	mustEmbedUnimplementedAccountManagementServer()
}

// UnimplementedAccountManagementServer must be embedded to have forward compatible implementations.
type UnimplementedAccountManagementServer struct {
}

func (UnimplementedAccountManagementServer) CreateAccount(context.Context, *NewAccount) (*Account, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedAccountManagementServer) GetAccount(context.Context, *GetAccountParams) (*AccountList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedAccountManagementServer) mustEmbedUnimplementedAccountManagementServer() {}

// UnsafeAccountManagementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountManagementServer will
// result in compilation errors.
type UnsafeAccountManagementServer interface {
	mustEmbedUnimplementedAccountManagementServer()
}

func RegisterAccountManagementServer(s grpc.ServiceRegistrar, srv AccountManagementServer) {
	s.RegisterService(&AccountManagement_ServiceDesc, srv)
}

func _AccountManagement_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewAccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagementServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_proto.AccountManagement/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagementServer).CreateAccount(ctx, req.(*NewAccount))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountManagement_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountManagementServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account_proto.AccountManagement/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountManagementServer).GetAccount(ctx, req.(*GetAccountParams))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountManagement_ServiceDesc is the grpc.ServiceDesc for AccountManagement service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountManagement_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "account_proto.AccountManagement",
	HandlerType: (*AccountManagementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _AccountManagement_CreateAccount_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _AccountManagement_GetAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account_proto/account.proto",
}
