---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    kubernetes.io/metadata.name: backend
    prometheus: watched
  name: backend
spec:
  finalizers:
  - kubernetes

---
apiVersion: v1
kind: Namespace
metadata:
  name: app
  labels:
    kubernetes.io/metadata.name: app
    prometheus: watched