
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-pvc
  namespace: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kops-csi-1-21
  resources:
    requests:
      storage: 10Gi