apiVersion: v1
kind: Service
metadata:
  name: pg-service
  namespace: backend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb" # not a good practice, for quick remote debug
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: LoadBalancer
